### ISSUE TITLE
No License file

### ISSUE THREAD

**Issue by dvhart** [nemec/gedit-git-plugin#3]
I was looking for something like this and rather than start from scratch I decided to give this one a shot. It's atrophied some with changes to Glib, Python3, Gedit, etc. I've got it working again in my fork in the python3 branch. I'd like to contribute this back to your branch (assuming you're still interested), but before I can do that, I need to ask you to provide a LICENSE file. GPLv2 seems appropriate to encourage contribution back, but I can work with most OSS Licenses. Is this something you'd be willing to add?

**Comment by dvhart** [comment]
And, after reading Issue #2, if you are no longer interested in maintaining this project, adding a LICENSE file will make it easier for me to fork and maintain independently. Thanks.

**Comment by nemec** [comment]
Done. MIT Licensed.

**Comment by nemec** [comment]
Also I don't think this project is big enough to be worth maintaining on my own page. If you feel you can take the code and build something great out of it, I think it will be easier for you to maintain an independent fork :)

**Comment by dvhart** [comment]
Thanks for responding and adding the license. Much appreciated. And thanks for sharing your project publicly, definitely sped things up for me.
