### ISSUE TITLE
Does not work with gedit 3.18.3 on Mint

### ISSUE THREAD

**Issue by kurdtpage** [nemec/gedit-git-plugin#4]
This plugin does not work using gedit version 3.18.3 on Linux Mint 18.1 using python 3.5.2

![gitedit](https://user-images.githubusercontent.com/1308716/29246362-97a21740-804b-11e7-9966-2f1172706957.png)

**Comment by dvhart** [comment]
Try my fork, it supports python 3 and later versions of Gnome. https://github.com/dvhart/gedit-git-plugin

**Comment by nemec** [comment]
Thanks, I edited the README with a link to your fork. @kurdtpage as you can probably tell, I don't use this plugin any more so I am not surprised it's broken. I hope @dvhart's fork works for you 🙂
